### ISSUE TITLE
/attempts endpoint does not work after introduction of Repositories

### ISSUE THREAD

**Issue by wagenbm** [Book-Microservices-v2/chapter05#4]
Hi Moisés,

After the introduction of the Repositories for the Users and Attempts, the /attempts endpoint does not work anymore. When calling it like this:

`http POST :8080/attempts factorA=58 factorB=92 userAlias=matthias guess=5303`

I am getting this response:

`{"timestamp"}`

There is even no http-code.

I also try it via Postman using this payload:

```
{
    "factorA":20,
    "factorB":50,
    "userAlias":"matthias",
    "guess":1000
}
```
Here, I am getting the same response as before and can see that there is an internal server error but without any details.

![image](https://user-images.githubusercontent.com/45208235/224548344-23be15b7-958a-4228-88f0-d65e007f5c54.png)

I double checked against your code in Git Hub, and cannot find a problem.

Before I added the Json Configuration, I got this error message:

`could not prepare statement; SQL [select u1_0.id, u1_0.alias from user u1_0 where u1_0.alias=?]`

Any idea what I am doing wrong?

Thanks and best regards,
Matthias

**Comment by wagenbm** [comment]
I found the reason: There was a dependency missing. I added this dependency which caused it works again:

```
		<dependency>
			<groupId>org.hibernate.javax.persistence</groupId>
			<artifactId>hibernate-jpa-2.1-api</artifactId>
			<version>1.0.0.Final</version>
    	       </dependency>
```

I overlooked the console output when sending the request:

```
...
Caused by: java.lang.ClassNotFoundException: javax.persistence.Transient
...
```

Best regards,
Matthias

**Comment by mechero** [comment]
Nice! I'm glad you found the solution, and thanks for posting it for other readers!
